# Generated by Django 4.1.7 on 2023-03-07 13:04

import django.core.validators
from django.db import migrations, models
import myapp.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("3adcbe53-cbed-42f6-aad1-fb63fd80b99d"),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("tags", models.CharField(max_length=100)),
                ("desc", models.CharField(max_length=150)),
                (
                    "file",
                    models.FileField(
                        upload_to="upload/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "pdf",
                                    "doc",
                                    "docs",
                                    "txt",
                                    "zip",
                                    ".py",
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "docx",
                                    "xls",
                                    "xlsx",
                                    "ppt",
                                    "pptx",
                                ]
                            ),
                            myapp.models.validate_file_size,
                        ],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "mid",
                    models.UUIDField(
                        default=uuid.UUID("26acae0b-61ed-4f48-a80a-4f4e1255d98a"),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
                ("heading", models.CharField(max_length=100)),
                ("message", models.TextField()),
                ("date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Library",
            fields=[
                ("name", models.CharField(max_length=20)),
                (
                    "library_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "username",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("libraryid", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=50)),
                ("age", models.IntegerField()),
                ("password", models.CharField(max_length=20)),
                ("married", models.BooleanField()),
            ],
        ),
    ]
