# Generated by Django 4.1.7 on 2023-03-07 23:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("b2c1684b-f77c-4524-8bf2-bbc2534ea700"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="mid",
            field=models.UUIDField(
                default=uuid.UUID("8deb9fcd-6cfc-40f7-87b6-b4975bd23d5b"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
