# Generated by Django 4.1.7 on 2023-03-09 04:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_alter_book_id_alter_feedback_mid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("263755e4-e14d-48e9-90e7-b7807a0ad1cc"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="mid",
            field=models.UUIDField(
                default=uuid.UUID("0cc4d8bd-7654-4adf-b1b7-5b4923d1b516"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
