# Generated by Django 4.1.7 on 2023-03-11 10:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_alter_book_id_alter_feedback_mid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("ba39591a-a510-4943-91c3-6cc05c1da77a"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="mid",
            field=models.UUIDField(
                default=uuid.UUID("03056db8-a9a0-44db-98e6-8cbc357b4b96"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="libraryid",
            field=models.UUIDField(),
        ),
    ]
