# Generated by Django 4.1.7 on 2023-03-11 11:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_alter_book_id_alter_feedback_mid_alter_user_married_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="Users",
        ),
        migrations.AlterField(
            model_name="book",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("02b808bb-c8b5-4c6a-89bf-fd3fca22b022"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="mid",
            field=models.UUIDField(
                default=uuid.UUID("f4b2fc85-81e7-423e-b21b-157d36b052a6"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
