# Generated by Django 4.1.7 on 2023-03-11 20:31

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_rename_user_users_alter_book_id_alter_feedback_mid"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="blevel",
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name="book",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="book",
            name="desc",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="book",
            name="id",
            field=models.CharField(
                editable=False,
                max_length=100,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="mid",
            field=models.UUIDField(
                default=uuid.UUID("eb4bb96a-d8e6-4b10-9852-36222c3243c3"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
