# Generated by Django 4.1.7 on 2023-03-12 08:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_book_blevel_book_date_alter_book_desc_alter_book_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="mid",
            field=models.UUIDField(
                default=uuid.UUID("24fb3c0b-1c13-4807-acfb-17154ec3e7ba"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
