# Generated by Django 4.1.7 on 2023-03-12 14:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_alter_feedback_mid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="mid",
            field=models.UUIDField(
                default=uuid.UUID("b059fdf8-6738-4e9d-800a-6110cf452159"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="library",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
