# Generated by Django 4.1.7 on 2023-03-12 14:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0010_alter_feedback_mid_alter_library_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="mid",
            field=models.UUIDField(
                default=uuid.UUID("9b46215a-05e1-459e-9c61-7649984b4ec0"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
