# Generated by Django 4.1.7 on 2023-03-12 16:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0011_alter_feedback_mid"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="userlevel",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="mid",
            field=models.UUIDField(
                default=uuid.UUID("3eff5615-0284-4c3b-9ecf-3d1a8ff0b4f0"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
