# Generated by Django 4.1.7 on 2023-03-13 10:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0013_alter_feedback_mid"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="libraryid",
            field=models.UUIDField(default=1),
        ),
        migrations.AddField(
            model_name="book",
            name="username",
            field=models.CharField(default="asjad", max_length=40),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="mid",
            field=models.UUIDField(
                default=uuid.UUID("8886c6e5-b11a-48cb-830a-504609d6a667"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
