# Generated by Django 4.1.7 on 2023-03-13 11:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0014_book_libraryid_book_username_alter_feedback_mid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="libraryid",
        ),
        migrations.AddField(
            model_name="book",
            name="libraryname",
            field=models.CharField(default="Lib1", max_length=40),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="mid",
            field=models.UUIDField(
                default=uuid.UUID("0542338d-a165-4a40-8c26-d88270aac850"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
