# Generated by Django 4.1.7 on 2023-03-28 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0017_remove_book_libraryname"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="libraryname",
            field=models.CharField(default="Lib1", max_length=50),
        ),
    ]
