# Generated by Django 4.1.7 on 2023-03-30 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0022_alter_book_file_alter_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.CharField(max_length=50),
        ),
    ]
