# Generated by Django 4.1.7 on 2023-05-12 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0023_alter_profile_user"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Book",
            new_name="Content",
        ),
    ]
