# Generated by Django 4.1.7 on 2023-05-12 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0024_rename_book_content"),
    ]

    operations = [
        migrations.RenameField(
            model_name="content",
            old_name="libraryname",
            new_name="libraryid",
        ),
    ]
