# Generated by Django 4.1.7 on 2023-05-12 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0025_rename_libraryname_content_libraryid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="content",
            old_name="libraryid",
            new_name="libraryname",
        ),
    ]
